import { Notebook } from './notebook.mjs';
import { MemoryLedger } from './memory-ledger.mjs';
import { ContextEngine } from './context-engine.mjs';
import { countTextTokens } from './context-budget.mjs';
import { DatabaseSync } from 'node:sqlite';
import { createHash, randomUUID } from 'node:crypto';
import { mkdirSync, writeFileSync, renameSync, existsSync, readFileSync, statSync, copyFileSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createNativeSnapshot, nativeSnapshotCapabilities, nativeSnapshotPath } from './native-snapshot.mjs';

export class ContinuityError extends Error {}
export class StaleRevision extends ContinuityError {}
export class EpochMismatch extends ContinuityError {}
export class ScopeError extends ContinuityError {}
export class GateError extends ContinuityError {}
export class CheckpointError extends ContinuityError {}
const id = p => `${p}_${randomUUID().replaceAll('-','')}`;
const now = () => Date.now()/1000;
const SECRET_KEY = /(?:api[-_]?key|authorization|access[-_]?token|refresh[-_]?token|password|secret)/i;
const redact = value => Array.isArray(value) ? value.map(redact) : (value && typeof value === 'object' ? Object.fromEntries(Object.entries(value).map(([k,v]) => [k, SECRET_KEY.test(k) ? '[REDACTED]' : redact(v)])) : value);
const compactImage = value => { const out = { kind: 'image', inline: false }; for (const key of ['assetId','asset_id','sha256','mimeType','mime_type','width','height','size','metadata','derived','caption','ocr','observations']) if (value[key] !== undefined) out[key] = value[key]; if (!out.assetId && value.id !== undefined) out.assetId = value.id; return out; };
const compactForContext = value => Array.isArray(value) ? value.map(compactForContext) : (value && typeof value === 'object' ? ((value.kind === 'image' || value.type === 'image' || String(value.mimeType ?? value.mime_type ?? value.mime ?? value.source?.media_type ?? '').toLowerCase().startsWith('image/')) ? compactImage(value) : Object.fromEntries(Object.entries(value).filter(([k]) => !['base64','data_uri'].includes(k)).map(([k,v]) => [k, compactForContext(v)]))) : value);
const compressionScalar = value => value == null ? '' : typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : JSON.stringify(compactForContext(value));
const compressionEventText = row => { let p; try { p = JSON.parse(row.payload); } catch { p = row.payload; } if (typeof p === 'string') return p; if (!p || typeof p !== 'object') return compressionScalar(p); return Object.entries(compactForContext(p)).filter(([,v]) => v !== undefined).map(([k,v]) => k === 'text' && typeof v === 'string' ? v : k + ': ' + compressionScalar(v)).join(' | '); };
const compressionImportance = row => { const text = compressionEventText(row).toLocaleLowerCase(); const weights = { user_input: 100, user_confirmation: 95, resume: 90, model_error: 90, operation_reconciliation: 88, tool_call: 72, tool_result: 70, model_response: 55, provider_request: 30, model_request: 25 }; return (weights[row.source] ?? 40) + (/(decision|constraint|fact|next step|next_step|error|failed|failure|blocked|must|重要|决定|约束|事实|下一步|失败|阻塞)/i.test(text) ? 20 : 0); };
const compressionMemoryScore = (memory, terms) => { const text = String(memory.scope) + ' ' + String(memory.subject) + ' ' + String(memory.predicate) + ' ' + compressionScalar(memory.value); const normalized = text.toLocaleLowerCase(); return terms.reduce((score, term) => score + (term && normalized.includes(term) ? 1 : 0), 0); };
const compressionCandidates = rows => { const out = []; const add = (predicate, value, eventId) => { const text = compressionScalar(value); if (text) out.push({ scope: 'task', subject: 'session', predicate, value: text, sourceEventId: eventId }); }; for (const row of rows) { let p; try { p = JSON.parse(row.payload); } catch { p = {}; } if (p && typeof p === 'object') for (const [key, predicate] of [['decision','decision'],['fact','fact'],['constraint','constraint'],['nextStep','next_step'],['next_step','next_step']]) if (p[key] !== undefined) add(predicate, p[key], row.event_id); const text = compressionEventText(row); for (const m of text.matchAll(/(?:^|[\n|])\s*(?:text\s*[:：]\s*)?(Decision|Fact|Constraint|Next step|Next_Step|决定|事实|约束|下一步)\s*[:：-]\s*([^\n|]+)/gim)) { const labels = { decision:'decision', fact:'fact', constraint:'constraint', 'next step':'next_step', next_step:'next_step', '决定':'decision', '事实':'fact', '约束':'constraint', '下一步':'next_step' }; add(labels[m[1].toLocaleLowerCase()], m[2], row.event_id); } } return out; };

export class ContinuityStore {
  constructor(path, {blobDir, mode='off', countTokens=countTextTokens, tokenCounterName='cl100k_base'}={}) {
    if (!['off','record','active'].includes(mode)) throw new Error('mode must be off, record, or active');
    if(typeof countTokens!=='function') throw new TypeError('countTokens must be a function');
    this.countTokens=countTokens; this.tokenCounterName=tokenCounterName;
    this.path=resolve(path); mkdirSync(dirname(this.path),{recursive:true});
    this.blobDir=resolve(blobDir ?? this.path.replace(/\.[^.]+$/,'.blobs')); mkdirSync(this.blobDir,{recursive:true}); this.mode=mode;
    this.db=new DatabaseSync(this.path); this.db.exec('PRAGMA foreign_keys=ON'); this.db.exec(`
      CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS tasks(task_id TEXT PRIMARY KEY,project_id TEXT NOT NULL,branch TEXT NOT NULL,epoch INTEGER NOT NULL,revision INTEGER NOT NULL,goal TEXT NOT NULL,acceptance TEXT NOT NULL,constraints_json TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS events(event_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,project_id TEXT NOT NULL,branch TEXT NOT NULL,seq INTEGER NOT NULL,epoch INTEGER NOT NULL,op_id TEXT,source TEXT NOT NULL,availability TEXT NOT NULL,payload TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE INDEX IF NOT EXISTS events_scope ON events(task_id,branch,epoch,seq);
      CREATE TABLE IF NOT EXISTS work_records(record_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,epoch INTEGER NOT NULL,kind TEXT NOT NULL,payload TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS manifests(manifest_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,revision INTEGER NOT NULL,epoch INTEGER NOT NULL,payload TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS checkpoints(checkpoint_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,revision INTEGER NOT NULL,epoch INTEGER NOT NULL,state TEXT NOT NULL,payload TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS operations(op_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,epoch INTEGER NOT NULL,kind TEXT NOT NULL,status TEXT NOT NULL,result TEXT,created_at REAL NOT NULL,updated_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS notes(note_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,project_id TEXT NOT NULL,branch TEXT NOT NULL,epoch INTEGER NOT NULL,scope TEXT NOT NULL,text TEXT NOT NULL,evidence_ids_json TEXT NOT NULL,status TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS memory_claims(memory_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,project_id TEXT NOT NULL,branch TEXT NOT NULL,epoch INTEGER NOT NULL,revision INTEGER NOT NULL,scope TEXT NOT NULL,subject TEXT NOT NULL,predicate TEXT NOT NULL,value_json TEXT NOT NULL,conflict_key TEXT NOT NULL,fingerprint TEXT NOT NULL,status TEXT NOT NULL,origin TEXT NOT NULL,evidence_ids_json TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE INDEX IF NOT EXISTS memory_claims_key ON memory_claims(task_id,project_id,branch,conflict_key,status);
      CREATE UNIQUE INDEX IF NOT EXISTS memory_claims_fingerprint ON memory_claims(task_id,fingerprint);
      CREATE TABLE IF NOT EXISTS memory_conflicts(conflict_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,project_id TEXT NOT NULL,branch TEXT NOT NULL,conflict_key TEXT NOT NULL,left_memory_id TEXT NOT NULL,right_memory_id TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE UNIQUE INDEX IF NOT EXISTS memory_conflict_pair ON memory_conflicts(task_id,left_memory_id,right_memory_id);
      CREATE TABLE IF NOT EXISTS memory_snapshots(snapshot_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,project_id TEXT NOT NULL,branch TEXT NOT NULL,epoch INTEGER NOT NULL,revision INTEGER NOT NULL,parent_ids_json TEXT NOT NULL,tree_hash TEXT NOT NULL,message TEXT NOT NULL,author TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS memory_snapshot_items(snapshot_id TEXT NOT NULL REFERENCES memory_snapshots,memory_id TEXT NOT NULL REFERENCES memory_claims,position INTEGER NOT NULL,PRIMARY KEY(snapshot_id,memory_id));
      CREATE TABLE IF NOT EXISTS memory_merge_proposals(merge_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,base_snapshot_id TEXT NOT NULL,ours_snapshot_id TEXT NOT NULL,theirs_snapshot_id TEXT NOT NULL,proposal_json TEXT NOT NULL,status TEXT NOT NULL,created_at REAL NOT NULL,updated_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS compression_views(view_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,project_id TEXT NOT NULL,branch TEXT NOT NULL,epoch INTEGER NOT NULL,revision INTEGER NOT NULL,strategy TEXT NOT NULL,source_event_ids_json TEXT NOT NULL,source_memory_ids_json TEXT NOT NULL,omitted_event_ids_json TEXT NOT NULL,payload_json TEXT NOT NULL,tokens_before INTEGER NOT NULL,tokens_after INTEGER NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS workspace_snapshots(snapshot_id TEXT PRIMARY KEY,task_id TEXT NOT NULL REFERENCES tasks,project_id TEXT NOT NULL,branch TEXT NOT NULL,epoch INTEGER NOT NULL,revision INTEGER NOT NULL,root TEXT NOT NULL,tree_hash TEXT NOT NULL,backend TEXT NOT NULL,message TEXT NOT NULL,author TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS workspace_snapshot_items(snapshot_id TEXT NOT NULL REFERENCES workspace_snapshots,item_path TEXT NOT NULL,kind TEXT NOT NULL,size INTEGER NOT NULL,mtime_ms REAL,mode INTEGER,sha256 TEXT,blob_id TEXT,PRIMARY KEY(snapshot_id,item_path));
      CREATE TABLE IF NOT EXISTS workspace_snapshot_native(snapshot_id TEXT PRIMARY KEY REFERENCES workspace_snapshots,backend TEXT NOT NULL,reference TEXT,device TEXT,root TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS blobs(blob_id TEXT PRIMARY KEY,sha256 TEXT NOT NULL,size INTEGER NOT NULL,path TEXT NOT NULL,created_at REAL NOT NULL);
      CREATE TABLE IF NOT EXISTS runtime_states(task_id TEXT PRIMARY KEY REFERENCES tasks,state TEXT NOT NULL,detail TEXT,updated_at REAL NOT NULL);
      INSERT OR IGNORE INTO meta VALUES('schema_version','4');`);
    const schema=this.row('SELECT value FROM meta WHERE key=?','schema_version')?.value;
    if(schema!=='4') throw new ContinuityError(`unsupported continuity schema ${schema}`);
    const errors={ContinuityError,StaleRevision,EpochMismatch,ScopeError,GateError,CheckpointError};
    this.notebook=new Notebook(this,errors);
    this.memory=new MemoryLedger(this,errors);
    this.contextEngine=new ContextEngine(this,errors);
    this.db.exec("UPDATE operations SET status='unknown', updated_at=strftime('%s','now') WHERE status='intent'");
  }
  close(){this.db.close()}
  row(sql,...args){return this.db.prepare(sql).get(...args)}
  setNativeSnapshotMode(mode){if(!['portable-cas','auto','native'].includes(mode))throw new ContinuityError('native snapshot mode must be portable-cas, auto, or native');this.db.prepare("INSERT INTO meta(key,value) VALUES('native_snapshot_mode',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(mode);return mode}
  nativeSnapshotMode(){return this.row("SELECT value FROM meta WHERE key='native_snapshot_mode'")?.value??'portable-cas'}
  tx(fn){
    this.transactionSequence=(this.transactionSequence??0)+1;
    const nested=this.db.isTransaction,savepoint='continuity_'+this.transactionSequence;
    this.db.exec(nested?'SAVEPOINT '+savepoint:'BEGIN IMMEDIATE');
    try{const result=fn();this.db.exec(nested?'RELEASE SAVEPOINT '+savepoint:'COMMIT');return result}
    catch(error){try{if(nested){this.db.exec('ROLLBACK TO SAVEPOINT '+savepoint);this.db.exec('RELEASE SAVEPOINT '+savepoint)}else this.db.exec('ROLLBACK')}catch{}throw error}
  }
  getTask(taskId, projectId, branch){const r=this.row('SELECT * FROM tasks WHERE task_id=?',taskId); if(!r || (projectId!==undefined&&r.project_id!==projectId)||(branch!==undefined&&r.branch!==branch)) throw new ScopeError('task scope mismatch'); return {...r,acceptance:JSON.parse(r.acceptance),constraints:JSON.parse(r.constraints_json)} }
  createTask(projectId,branch,goal,{acceptance=[],constraints=[],taskId=id('task')}={}){this.tx(()=>{this.db.prepare('INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?,?)').run(taskId,projectId,branch,1,1,goal,JSON.stringify(acceptance),JSON.stringify(constraints),now()); this.db.prepare('INSERT INTO runtime_states VALUES(?,?,?,?)').run(taskId,'RUNNING',null,now()); this.recordEvent(taskId,'user_input',{goal,acceptance,constraints},{epoch:1});}); return this.getTask(taskId)}
  runtimeState(taskId){this.getTask(taskId);return this.row('SELECT * FROM runtime_states WHERE task_id=?',taskId)}
  transition(taskId,state,detail=null){const allowed={RUNNING:['QUIESCING','FAILED','RECOVERY_REQUIRED'],QUIESCING:['PERSISTING','FAILED','RECOVERY_REQUIRED'],PERSISTING:['BUILDING','FAILED','RECOVERY_REQUIRED'],BUILDING:['VALIDATING','FAILED','RECOVERY_REQUIRED'],VALIDATING:['READY','FAILED','RECOVERY_REQUIRED'],READY:['RUNNING','QUIESCING'],FAILED:['RECOVERY_REQUIRED','RUNNING'],RECOVERY_REQUIRED:['RUNNING']};const current=this.runtimeState(taskId)?.state;if(!current||!allowed[current]?.includes(state))throw new CheckpointError(`invalid state transition ${current} -> ${state}`);this.db.prepare('UPDATE runtime_states SET state=?,detail=?,updated_at=? WHERE task_id=?').run(state,detail,now(),taskId);return this.runtimeState(taskId)}
  startRun(taskId){const state=this.runtimeState(taskId)?.state;if(state==='READY')return this.transition(taskId,'RUNNING');if(state!=='RUNNING')throw new GateError(`continuity runtime state is ${state}`);return this.runtimeState(taskId)}
  updateContract(taskId,expectedRevision,epoch,{constraints,acceptance,goal,confirmed=false,sourceEvent}={}){const t=this.getTask(taskId);if(t.revision!==expectedRevision)throw new StaleRevision('stale revision');if(t.epoch!==epoch)throw new EpochMismatch('stale epoch');const c=constraints??t.constraints,a=acceptance??t.acceptance,g=goal??t.goal;if(!confirmed){this.recordEvent(taskId,'model_proposal',{goal:g,acceptance:a,constraints:c,confirmed:false,sourceEvent},{epoch});return this.getTask(taskId)}if(!sourceEvent||!['user','host'].includes(sourceEvent.actor))throw new ContinuityError('confirmed changes require an explicit user/host source event');return this.tx(()=>{this.db.prepare('UPDATE tasks SET revision=revision+1,goal=?,acceptance=?,constraints_json=? WHERE task_id=? AND revision=? AND epoch=?').run(g,JSON.stringify(a),JSON.stringify(c),taskId,expectedRevision,epoch);this.recordEvent(taskId,'user_confirmation',{goal:g,acceptance:a,constraints:c,confirmed:true,sourceEvent},{epoch});return this.getTask(taskId)})}
  correct(taskId,expectedRevision,epoch,change){return this.updateContract(taskId,expectedRevision,epoch,{...change,confirmed:true})}
  bumpEpoch(taskId,expectedRevision){const t=this.getTask(taskId);if(t.revision!==expectedRevision)throw new StaleRevision('stale revision');this.db.prepare('UPDATE tasks SET epoch=epoch+1 WHERE task_id=? AND revision=?').run(taskId,expectedRevision);this.db.prepare("UPDATE runtime_states SET state='RUNNING',detail=NULL,updated_at=? WHERE task_id=?").run(now(),taskId);return this.getTask(taskId)}
  recordEvent(taskId,source,payload,{epoch,opId=null,availability='captured'}={}){const t=this.getTask(taskId);epoch??=t.epoch;if(epoch!==t.epoch)throw new EpochMismatch('cannot write stale epoch');const seq=this.row('SELECT COALESCE(MAX(seq),0)+1 AS n FROM events WHERE task_id=?',taskId).n,eventId=id('evt'),safe=redact(this._prepareImagePayload(payload)),encoded=JSON.stringify(safe);let stored=safe;if(Buffer.byteLength(encoded,'utf8')>12000){const blobId=this.saveBlob(encoded);stored={blobId,bytes:Buffer.byteLength(encoded,'utf8'),preview:encoded.slice(0,1600),truncated:true};availability=availability==='captured'?'captured':availability}this.db.prepare('INSERT INTO events VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(eventId,taskId,t.project_id,t.branch,seq,epoch,opId,source,availability,JSON.stringify(stored),now());return eventId}
  recordWork(taskId,kind,payload,{epoch}={}){const t=this.getTask(taskId);epoch??=t.epoch;if(epoch!==t.epoch)throw new EpochMismatch('cannot write stale epoch');const rid=id('work'),safe=redact(payload),encoded=JSON.stringify(safe);let stored=safe;if(Buffer.byteLength(encoded,'utf8')>12000){const blobId=this.saveBlob(encoded);stored={blobId,bytes:Buffer.byteLength(encoded,'utf8'),preview:encoded.slice(0,1600),truncated:true}}this.db.prepare('INSERT INTO work_records VALUES(?,?,?,?,?,?)').run(rid,taskId,epoch,kind,JSON.stringify(stored),now());return rid}
  captureWorkspace(root,files=[]){const base=resolve(root),entries=[];for(const rel of files){const path=resolve(base,rel),inside=relative(base,path);if(inside.startsWith('..')||inside.startsWith('/')||/^[A-Za-z]:/.test(inside))throw new ScopeError(`workspace path escapes root: ${rel}`);try{const st=statSync(path);const data=st.isFile()?readFileSync(path):Buffer.from('');entries.push({path:rel.replaceAll('\\','/'),kind:st.isFile()?'file':'directory',size:st.size,mtimeMs:st.mtimeMs,sha256:createHash('sha256').update(data).digest('hex')})}catch{entries.push({path:rel.replaceAll('\\','/'),kind:'missing'})}}let gitHead='unknown',dirty='unknown';try{const io={encoding:'utf8',stdio:['ignore','pipe','ignore']};gitHead=execFileSync('git',['-C',base,'rev-parse','HEAD'],io).trim();dirty=execFileSync('git',['-C',base,'status','--porcelain','--untracked-files=all'],io).trim()?'dirty':'clean'}catch{}const snapshot={root:base,files:entries,gitHead,dirty,coverage:files.length?'selected':'none'};snapshot.fingerprint=createHash('sha256').update(JSON.stringify(snapshot)).digest('hex');return snapshot}
  compareWorkspace(expected,current){if(!expected||!current)return {status:'unknown',reason:'missing snapshot'};if(expected.fingerprint===current.fingerprint)return {status:'match'};if(expected.root!==current.root)return {status:'mismatch',reason:'root changed'};return {status:'mismatch',reason:'selected files, git state, or fingerprint changed'}}
  nativeSnapshotCapabilities(root){return nativeSnapshotCapabilities(root)}
  createWorkspaceSnapshot(taskId,{epoch,revision,root,files=[],message='workspace snapshot',author='host',backend}={}){const t=this.getTask(taskId);epoch??=t.epoch;revision??=t.revision;backend??=this.nativeSnapshotMode();if(epoch!==t.epoch)throw new EpochMismatch('stale workspace snapshot epoch');if(revision!==t.revision)throw new StaleRevision('stale workspace snapshot revision');const base=resolve(root),native=backend==='native'?createNativeSnapshot(base,{backend:'auto'}):backend==='auto'?(()=>{try{return createNativeSnapshot(base,{backend:'auto'})}catch{return null}})():null,items=[];for(const rel of files){const path=resolve(base,rel),inside=relative(base,path);if(inside.startsWith('..')||inside.startsWith('/')||/^[A-Za-z]:/.test(inside))throw new ScopeError(`workspace path escapes root: ${rel}`);try{const st=statSync(path),itemPath=rel.replaceAll('\\','/');if(st.isFile()){const data=readFileSync(path),blobId=this.saveBlob(data,{redactSecrets:false}),sha=createHash('sha256').update(data).digest('hex');items.push({itemPath,kind:'file',size:st.size,mtimeMs:st.mtimeMs,mode:st.mode,sha256:sha,blobId})}else items.push({itemPath,kind:'directory',size:st.size,mtimeMs:st.mtimeMs,mode:st.mode,sha256:null,blobId:null})}catch{items.push({itemPath:rel.replaceAll('\\','/'),kind:'missing',size:0,mtimeMs:null,mode:null,sha256:null,blobId:null})}}const treeHash=createHash('sha256').update(JSON.stringify(items.map(({itemPath,kind,size,mtimeMs,mode,sha256})=>({itemPath,kind,size,mtimeMs,mode,sha256})))).digest('hex'),snapshotId=id('wsnap'),effectiveBackend=native?.backend??'portable-cas';this.tx(()=>{this.db.prepare('INSERT INTO workspace_snapshots(snapshot_id,task_id,project_id,branch,epoch,revision,root,tree_hash,backend,message,author,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(snapshotId,taskId,t.project_id,t.branch,epoch,revision,base,treeHash,effectiveBackend,String(message),String(author),now());for(const item of items)this.db.prepare('INSERT INTO workspace_snapshot_items VALUES(?,?,?,?,?,?,?,?)').run(snapshotId,item.itemPath,item.kind,item.size,item.mtimeMs,item.mode,item.sha256,item.blobId);if(native)this.db.prepare('INSERT INTO workspace_snapshot_native VALUES(?,?,?,?,?,?)').run(snapshotId,native.backend,native.reference,native.device,native.root,now())});return this.workspaceSnapshot(snapshotId,taskId)}
  workspaceSnapshot(snapshotId,taskId){const row=this.row('SELECT * FROM workspace_snapshots WHERE snapshot_id=?',snapshotId);if(!row||row.task_id!==taskId)throw new ScopeError('workspace snapshot scope mismatch');const items=this.db.prepare('SELECT * FROM workspace_snapshot_items WHERE snapshot_id=? ORDER BY item_path').all(snapshotId).map(x=>({...x})),native=this.row('SELECT * FROM workspace_snapshot_native WHERE snapshot_id=?',snapshotId);return {...row,items,native:native??null}}
  readWorkspaceSnapshotFile(snapshotId,taskId,itemPath){const snap=this.workspaceSnapshot(snapshotId,taskId),rel=String(itemPath).replaceAll('\\','/'),item=snap.items.find(x=>x.item_path===rel);if(!item||item.kind!=='file')throw new ScopeError('workspace snapshot file not found');const nativePath=nativeSnapshotPath(snap.native,rel);if(nativePath&&existsSync(nativePath))return readFileSync(nativePath);const blob=this.row('SELECT path FROM blobs WHERE blob_id=?',item.blob_id);if(!blob||!existsSync(blob.path))throw new CheckpointError('workspace snapshot blob is missing');return readFileSync(blob.path)}
  _prepareImagePayload(value){if(Array.isArray(value))return value.map(item=>this._prepareImagePayload(item));if(!value||typeof value!=='object')return value;const source=value.source&&typeof value.source==='object'?value.source:null;const media=String(value.mimeType??value.mime_type??value.mime??source?.media_type??source?.mime_type??'').toLowerCase();const encoded=typeof source?.data==='string'?source.data:(value.type==='image'&&typeof value.data==='string'?value.data:null);if(media.startsWith('image/')&&encoded){const raw=encoded.replace(/^data:[^;]+;base64,/,'');const buf=Buffer.from(raw,'base64');if(buf.length){const ref={kind:'image',assetId:this.saveBlob(buf,{redactSecrets:false}),mimeType:media,size:buf.length,inline:false};for(const key of ['width','height','metadata','derived','caption','ocr','observations'])if(value[key]!==undefined)ref[key]=value[key];return ref}}return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,this._prepareImagePayload(item)]))}
  saveBlob(data,{redactSecrets=true}={}){let value=data;if(redactSecrets&&!Buffer.isBuffer(data)&&typeof data==='string'){try{value=JSON.stringify(redact(JSON.parse(data)))}catch{}}const buf=Buffer.isBuffer(value)?value:Buffer.from(value),sha=createHash('sha256').update(buf).digest('hex'),final=join(this.blobDir,sha);if(!existsSync(final)){const tmp=join(this.blobDir,`.tmp-${randomUUID()}`);writeFileSync(tmp,buf,{flag:'wx'});renameSync(tmp,final)}const bid=id('blob');this.db.prepare('INSERT INTO blobs VALUES(?,?,?,?,?)').run(bid,sha,buf.length,final,now());return bid}

  loadBlob(blobId){const row=this.row('SELECT path FROM blobs WHERE blob_id=?',blobId);if(!row||!existsSync(row.path))throw new CheckpointError('blob is missing');return readFileSync(row.path)}
  recordImage(taskId,data,{assetId=null,mimeType,width,height,caption,ocr,observations,metadata,epoch}={}){if(data==null&&!assetId)throw new ContinuityError('image data or assetId is required');if(data!=null)assetId=this.saveBlob(data,{redactSecrets:false});const ref={kind:'image',assetId,inline:false};if(mimeType)ref.mimeType=mimeType;if(width!=null)ref.width=width;if(height!=null)ref.height=height;if(data!=null)ref.size=Buffer.byteLength(data);if(metadata)ref.metadata=metadata;const derived=Object.fromEntries(Object.entries({caption,ocr,observations}).filter(([,v])=>v!==undefined));if(Object.keys(derived).length)ref.derived=derived;this.recordEvent(taskId,'image',ref,{epoch});return ref}
  beginOperation(taskId,epoch,kind,opId=id('op')){const t=this.getTask(taskId);if(t.epoch!==epoch)throw new EpochMismatch('stale epoch');const existing=this.row('SELECT * FROM operations WHERE op_id=?',opId);if(existing){if(existing.task_id!==taskId||existing.epoch!==epoch)throw new ScopeError('operation scope mismatch');return opId}this.db.prepare('INSERT INTO operations VALUES(?,?,?,?,?,?,?,?)').run(opId,taskId,epoch,kind,'intent',null,now(),now());return opId}
  operation(opId){return this.row('SELECT * FROM operations WHERE op_id=?',opId)}
  reconcileOperation(taskId,epoch,opId,status,result,{actor='host',sourceEvent}={}){const t=this.getTask(taskId);if(t.epoch!==epoch)throw new EpochMismatch('stale operation reconciliation');if(!['succeeded','failed'].includes(status))throw new ContinuityError('invalid reconciliation status');if(!sourceEvent||sourceEvent.actor!==actor||!['user','host'].includes(actor))throw new ContinuityError('operation reconciliation requires an explicit user/host source event');const op=this.operation(opId);if(!op||op.task_id!==taskId||op.epoch!==epoch)throw new ScopeError('operation scope mismatch');if(op.status!=='unknown')throw new ContinuityError(`operation ${opId} is not unknown`);this.tx(()=>{this.db.prepare('UPDATE operations SET status=?,result=?,updated_at=? WHERE op_id=? AND task_id=? AND epoch=? AND status=\'unknown\'').run(status,JSON.stringify(redact(result)),now(),opId,taskId,epoch);this.recordEvent(taskId,'operation_reconciliation',{opId,status,result,sourceEvent},{epoch,opId})});return this.operation(opId)}
  recordNote(taskId,epoch,text,{scope='task',evidenceIds=[],status='proposed',sourceEvent}={}){const t=this.getTask(taskId);if(t.epoch!==epoch)throw new EpochMismatch('stale note epoch');if(!['proposed','confirmed','retired'].includes(status))throw new ContinuityError('invalid note status');if(status==='confirmed'&&(!sourceEvent||!['user','host'].includes(sourceEvent.actor)))throw new ContinuityError('confirmed notes require an explicit user/host source event');const noteId=id('note');this.db.prepare('INSERT INTO notes VALUES(?,?,?,?,?,?,?,?,?,?)').run(noteId,taskId,t.project_id,t.branch,epoch,scope,String(text),JSON.stringify(evidenceIds),status,now());this.recordEvent(taskId,'note_'+status,{noteId,scope,text,evidenceIds,sourceEvent},{epoch});return this.note(noteId,taskId)}
  note(noteId,taskId){const r=this.row('SELECT * FROM notes WHERE note_id=?',noteId);if(!r||r.task_id!==taskId)throw new ScopeError('note scope mismatch');return {...r,evidenceIds:JSON.parse(r.evidence_ids_json)}}
  notes(taskId,epoch){
    const t=this.getTask(taskId); epoch??=t.epoch;
    if(epoch!==t.epoch)throw new ScopeError('only active epoch notes are readable');
    const inherited=(this.notebook.resumeContext(taskId).noteIds??[]).map(noteId=>this.note(noteId,taskId));
    const current=this.db.prepare("SELECT n.* FROM notes n WHERE n.task_id=? AND n.epoch=? AND n.status<>'retired' AND NOT EXISTS(SELECT 1 FROM notebook_entries b WHERE b.note_id=n.note_id) ORDER BY n.created_at DESC,n.note_id").all(taskId,epoch).map(r=>({...r,evidenceIds:JSON.parse(r.evidence_ids_json)}));
    return [...new Map([...inherited,...current].map(note=>[note.note_id,note])).values()];
  }
  refreshNotebook(taskId){return this.notebook.refresh(taskId)}
  notebookEntries(taskId,options){return this.notebook.read(taskId,options)}
  recordNotebookEntry(taskId,epoch,change){return this.notebook.put(taskId,epoch,change)}
  observeNotebook(taskId,observer,options){return this.notebook.observe(taskId,observer,options)}
  exportNotebook(taskId){this.refreshNotebook(taskId);return this.notebook.markdown(taskId)}
  readEvent(taskId,eventId){return this.notebook.source(taskId,eventId)}
  normalizeMemoryClaim({scope='task',subject,predicate,value}){if(subject===undefined||predicate===undefined||value===undefined)throw new ContinuityError('memory claims require subject, predicate, and value');const normText=v=>String(v).trim().toLocaleLowerCase().replace(/\s+/g,' '),normValue=v=>Array.isArray(v)?v.map(normValue):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>[normText(k),normValue(x)])):typeof v==='string'?normText(v):v;const normalized={scope:normText(scope),subject:normText(subject),predicate:normText(predicate),value:normValue(value)},conflictKey=createHash('sha256').update(JSON.stringify({scope:normalized.scope,subject:normalized.subject,predicate:normalized.predicate})).digest('hex'),fingerprint=createHash('sha256').update(JSON.stringify(normalized)).digest('hex');return {...normalized,conflictKey,fingerprint}}
  memoryClaim(memoryId,taskId){return this.memory.read(memoryId,taskId)}
  readMemory(memoryId,taskId){return this.memory.read(memoryId,taskId)}
  memoryClaims(taskId,options={}){return this.memory.list(taskId,options)}
  recallMemory(taskId,query,{limit=8,scope,includeCandidates=false,includeHistory=false}={}){
    this.getTask(taskId);
    const terms=String(query??'').trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
    if(!terms.length)return [];
    return this.memoryClaims(taskId,{includeCandidates,includeHistory}).filter(memory=>!scope||memory.scope===scope).map(memory=>{
      const text=[memory.scope,memory.subject,memory.predicate,JSON.stringify(memory.value)].join(' ').toLocaleLowerCase();
      return {...memory,score:terms.filter(term=>text.includes(term)).length/terms.length,preview:text.slice(0,500)};
    }).filter(memory=>memory.score>0).sort((a,b)=>b.score-a.score||a.memory_id.localeCompare(b.memory_id)).slice(0,Math.max(1,Math.min(64,Number(limit)||8)));
  }
  recordMemoryClaim(taskId,epoch,change={}){return this.memory.record(taskId,epoch,change)}
  memoryConflicts(taskId,options={}){return this.memory.conflicts(taskId,options)}
  memorySnapshot(snapshotId,taskId){return this.memory.snapshot(snapshotId,taskId)}
  createMemorySnapshot(taskId,options={}){return this.memory.createSnapshot(taskId,options)}
  forkMemorySnapshot(snapshotId,taskId,options={}){
    const snapshot=this.memorySnapshot(snapshotId,taskId);
    return this.createMemorySnapshot(taskId,{parentIds:[snapshot.snapshot_id],...options,versionIds:options.versionIds??(options.memoryIds?undefined:snapshot.memories.map(memory=>memory.version_id))});
  }
  memorySnapshotAncestors(snapshotId,taskId,{limit=256}={}){const seen=new Set(),queue=[snapshotId];while(queue.length&&seen.size<limit){const current=queue.shift();if(seen.has(current))continue;const snapshot=this.memorySnapshot(current,taskId);seen.add(current);queue.push(...snapshot.parentIds)}return seen}
  proposeMemoryMerge(taskId,{baseSnapshotId,oursSnapshotId,theirsSnapshotId,agent='agent'}={}){const base=this.memorySnapshot(baseSnapshotId,taskId),ours=this.memorySnapshot(oursSnapshotId,taskId),theirs=this.memorySnapshot(theirsSnapshotId,taskId);if(!this.memorySnapshotAncestors(ours.snapshot_id,taskId).has(base.snapshot_id)||!this.memorySnapshotAncestors(theirs.snapshot_id,taskId).has(base.snapshot_id))throw new CheckpointError('merge base must be an ancestor of both snapshots');const maps=[base,ours,theirs].map(s=>new Map(s.memories.map(m=>[m.conflict_key,m]))),keys=new Set(maps.flatMap(m=>[...m.keys()])),claimIds=[],conflicts=[];for(const key of keys){const [b,o,t]=maps.map(m=>m.get(key)),same=(x,y)=>x?.fingerprint===y?.fingerprint;let chosen;if(same(o,t))chosen=o;else if(same(o,b))chosen=t;else if(same(t,b))chosen=o;else if(!o&&t)chosen=t;else if(o&&!t)chosen=o;else {const candidates=[o,t].filter(Boolean);chosen=candidates.sort((a,z)=>(z.created_at??0)-(a.created_at??0)||z.memory_id.localeCompare(a.memory_id))[0];conflicts.push({conflictKey:key,memoryIds:candidates.map(x=>x.memory_id),selectedMemoryId:chosen?.memory_id,subject:candidates[0]?.subject,predicate:candidates[0]?.predicate,baseMemoryId:b?.memory_id,oursMemoryId:o?.memory_id,theirsMemoryId:t?.memory_id,candidates:candidates.map(x=>({memoryId:x.memory_id,value:x.value,evidenceIds:x.evidenceIds,status:x.status}))});}if(chosen)claimIds.push(chosen.memory_id)}const proposal={agent,baseSnapshotId,oursSnapshotId,theirsSnapshotId,claimIds:[...new Set(claimIds)],conflicts};const mergeId=id('merge');const t=this.getTask(taskId);this.db.prepare('INSERT INTO memory_merge_proposals VALUES(?,?,?,?,?,?,?,?,?)').run(mergeId,taskId,baseSnapshotId,oursSnapshotId,theirsSnapshotId,JSON.stringify(proposal),'ready',now(),now());return {mergeId,status:'ready',...proposal}}
  memoryMergeProposal(mergeId,taskId){const r=this.row('SELECT * FROM memory_merge_proposals WHERE merge_id=?',mergeId);if(!r||r.task_id!==taskId)throw new ScopeError('memory merge scope mismatch');return {...r,proposal:JSON.parse(r.proposal_json)}}
  commitMemoryMerge(taskId,mergeId,{expectedRevision,epoch,message='memory merge',author='host',resolutions={},sourceEvent}={}){
    return this.tx(()=>{
      const record=this.memoryMergeProposal(mergeId,taskId),task=this.getTask(taskId);
      expectedRevision??=task.revision;epoch??=task.epoch;
      if(epoch!==task.epoch)throw new EpochMismatch('stale memory merge epoch');
      if(expectedRevision!==task.revision)throw new StaleRevision('stale memory merge revision');
      if(record.status==='committed')throw new ContinuityError('memory merge proposal is already committed');
      const proposal=record.proposal,selected=new Set(proposal.claimIds);
      const snapshots=[this.memorySnapshot(record.base_snapshot_id,taskId),this.memorySnapshot(record.ours_snapshot_id,taskId),this.memorySnapshot(record.theirs_snapshot_id,taskId)];
      const versions=new Map(snapshots.flatMap(snapshot=>snapshot.memories.map(memory=>[memory.memory_id,memory.version_id])));
      for(const conflict of proposal.conflicts){
        const choice=resolutions[conflict.conflictKey]??conflict.selectedMemoryId??conflict.memoryIds[0];
        if(!conflict.memoryIds.includes(choice))throw new ScopeError('merge resolution must reference a conflict candidate');
        for(const memoryId of conflict.memoryIds)selected.delete(memoryId);
        selected.add(choice);
      }
      const snapshot=this.createMemorySnapshot(taskId,{epoch,revision:expectedRevision,parentIds:[record.ours_snapshot_id,record.theirs_snapshot_id],versionIds:[...selected].map(memoryId=>versions.get(memoryId)),message,author});
      this.db.prepare("UPDATE memory_merge_proposals SET status='committed',updated_at=? WHERE merge_id=? AND task_id=?").run(now(),mergeId,taskId);
      this.recordEvent(taskId,'memory_merge_committed',{mergeId,snapshotId:snapshot.snapshot_id,resolutions,sourceEvent},{epoch});
      return snapshot;
    });
  }
  compressContext(taskId,options){return this.contextEngine.compressContext(taskId,options)}
  compressionView(viewId,taskId){const row=this.row('SELECT * FROM compression_views WHERE view_id=?',viewId);if(!row||row.task_id!==taskId)throw new ScopeError('compression view scope mismatch');return {...row,sourceEventIds:JSON.parse(row.source_event_ids_json),sourceMemoryIds:JSON.parse(row.source_memory_ids_json),omittedEventIds:JSON.parse(row.omitted_event_ids_json),payload:JSON.parse(row.payload_json)};}
  expandCompressionView(viewId,taskId,{includeOmitted=false}={}){const view=this.compressionView(viewId,taskId),ids=includeOmitted?view.sourceEventIds:(view.payload.keptEventIds??[]),events=ids.length?this.db.prepare(`SELECT * FROM events WHERE task_id=? AND event_id IN (${ids.map(()=>'?').join(',')}) ORDER BY seq`).all(taskId,...ids):[],memories=view.payload.sourceMemoryVersionIds?view.payload.sourceMemoryVersionIds.map(versionId=>this.memory.version(versionId,taskId)):view.sourceMemoryIds.map(memoryId=>this.memoryClaim(memoryId,taskId));return {view,events,memories};}
  compressMemorySnapshot(snapshotId,taskId,{maxClaims=32}={}){const snapshot=this.memorySnapshot(snapshotId,taskId),groups=new Map();for(const claim of snapshot.memories){const key=claim.conflict_key;const group=groups.get(key)??{scope:claim.scope,subject:claim.subject,predicate:claim.predicate,values:[],memoryIds:[]};group.values.push(claim.value);group.memoryIds.push(claim.memory_id);groups.set(key,group)}const entries=[...groups.values()].sort((a,b)=>a.subject.localeCompare(b.subject)||a.predicate.localeCompare(b.predicate));return {format:'pi-continuity-memory-compression-v1',snapshotId,claimCount:snapshot.memories.length,groups:entries.slice(0,Math.max(1,Number(maxClaims)||32)),truncated:entries.length>maxClaims}}
  exportMemory(taskId,{snapshotId=null}={}){const t=this.getTask(taskId),snapshot=snapshotId?this.memorySnapshot(snapshotId,taskId):this.createMemorySnapshot(taskId,{message:'portable export',author:'host'});return {format:'pi-continuity-memory-bundle-v1',projectId:t.project_id,branch:t.branch,taskId,sourceSnapshot:{snapshotId:snapshot.snapshot_id,parentIds:snapshot.parentIds,epoch:snapshot.epoch,revision:snapshot.revision,message:snapshot.message,author:snapshot.author,createdAt:snapshot.created_at},claims:snapshot.memories.map(({value_json,evidence_ids_json,...claim})=>({scope:claim.scope,subject:claim.subject,predicate:claim.predicate,value:claim.value,status:claim.status,evidenceIds:claim.evidenceIds,createdAt:claim.created_at}))}}
  importMemory(taskId,epoch,bundle,{scopePrefix='' }={}){if(!bundle||bundle.format!=='pi-continuity-memory-bundle-v1')throw new ContinuityError('unsupported memory bundle');const imported=[];for(const claim of bundle.claims??[]){const result=this.recordMemoryClaim(taskId,epoch,{scope:scopePrefix?`${scopePrefix}:${claim.scope}`:claim.scope,subject:claim.subject,predicate:claim.predicate,value:claim.value,evidenceIds:claim.evidenceIds??[],status:claim.status==='proposed'?'proposed':'confirmed'});imported.push(result.memory)}const snapshot=this.createMemorySnapshot(taskId,{epoch,parentIds:[],memoryIds:imported.map(x=>x.memory_id),message:`import from ${bundle.projectId??'external system'}`,author:'import'});return {snapshot,claims:imported}}
  backup(destination){const out=resolve(destination);mkdirSync(dirname(out),{recursive:true});const blobs=this.db.prepare('SELECT sha256,path FROM blobs').all();for(const row of blobs)if(!existsSync(row.path))throw new CheckpointError(`referenced blob is missing: ${row.sha256}`);this.db.prepare('VACUUM INTO ?').run(out);const outBlobs=out.replace(/\.[^.]+$/,'.blobs');mkdirSync(outBlobs,{recursive:true});for(const row of blobs)copyFileSync(row.path,join(outBlobs,row.sha256));return {database:out,blobs:outBlobs}}
  finishOperation(taskId,epoch,opId,status,result){const t=this.getTask(taskId);if(t.epoch!==epoch)throw new EpochMismatch('late operation result');if(!['succeeded','failed'].includes(status))throw new ContinuityError('invalid operation result status');const op=this.operation(opId);if(!op||op.task_id!==taskId||op.epoch!==epoch)throw new ScopeError('operation scope mismatch');if(op.status==='unknown')throw new GateError(`operation ${opId} is unknown; reconcile before retry`);if(op.status!=='intent')return op;this.tx(()=>{this.db.prepare('UPDATE operations SET status=?,result=?,updated_at=? WHERE op_id=? AND task_id=? AND epoch=? AND status=?').run(status,JSON.stringify(redact(result)),now(),opId,taskId,epoch,'intent');this.recordEvent(taskId,'tool_result',{opId,status,result},{epoch,opId})});return this.operation(opId)}
  buildManifest(taskId,options){return this.contextEngine.buildManifest(taskId,options)}
  createCheckpoint(taskId,{expectedRevision,epoch,workspace,pending=[],notes=[],memorySnapshotId=null,publish=true}){
    const t=this.getTask(taskId);
    if(t.revision!==expectedRevision)throw new StaleRevision('checkpoint revision changed');
    if(t.epoch!==epoch)throw new EpochMismatch('checkpoint epoch changed');
    if(!workspace||typeof workspace!=='object')throw new CheckpointError('workspace description required');
    if(memorySnapshotId){const snap=this.memorySnapshot(memorySnapshotId,taskId);if(snap.epoch!==epoch||snap.revision!==expectedRevision)throw new CheckpointError('memory snapshot version does not match checkpoint')}
    this.refreshNotebook(taskId);
    const notebookIds=this.notebook.snapshot(taskId),noteIds=this.notes(taskId,epoch).map(n=>n.note_id);
    const memoryVersionIds=(memorySnapshotId?this.memorySnapshot(memorySnapshotId,taskId).memories:this.memoryClaims(taskId,{includeCandidates:true})).map(memory=>memory.version_id);
    const observerPending=this.notebook.observerState(taskId).rows.map(row=>({eventId:row.event_id,offset:row.offset}));
    const visibleSeq=this.row('SELECT COALESCE(MAX(seq),0) AS n FROM events WHERE task_id=? AND epoch=?',taskId,epoch).n;
    const cid=id('ckpt'),payload={taskId,revision:expectedRevision,epoch,workspace,pending,notes,memorySnapshotId,memoryVersionIds,notebookIds,noteIds,observerPending,visibleSeq,format:3};
    this.db.prepare('INSERT INTO checkpoints VALUES(?,?,?,?,?,?,?)').run(cid,taskId,expectedRevision,epoch,'BUILDING',JSON.stringify(payload),now());
    if(!publish)return cid;
    try{this.db.prepare("UPDATE checkpoints SET state='READY' WHERE checkpoint_id=?").run(cid)}catch(e){this.db.prepare("UPDATE checkpoints SET state='FAILED' WHERE checkpoint_id=?").run(cid);throw e}
    return cid;
  }
  handoff(taskId,{expectedRevision,epoch,workspace,pending=[],notes=[],memorySnapshotId=null}){let cid;try{this.transition(taskId,'QUIESCING');this.transition(taskId,'PERSISTING');this.transition(taskId,'BUILDING');cid=this.createCheckpoint(taskId,{expectedRevision,epoch,workspace,pending,notes,memorySnapshotId,publish:false});this.transition(taskId,'VALIDATING');this.db.prepare("UPDATE checkpoints SET state='READY' WHERE checkpoint_id=? AND state='BUILDING'").run(cid);this.transition(taskId,'READY');return cid}catch(e){if(cid)this.db.prepare("UPDATE checkpoints SET state='FAILED' WHERE checkpoint_id=? AND state='BUILDING'").run(cid);try{this.transition(taskId,'FAILED',String(e))}catch{}throw e}}
  checkpoint(cid){const r=this.row('SELECT * FROM checkpoints WHERE checkpoint_id=?',cid);return r?{...r,payload:JSON.parse(r.payload)}:null}
  inspect(cid,taskId){const c=this.checkpoint(cid);if(!c||c.task_id!==taskId)throw new ScopeError('checkpoint scope mismatch');return c}
  forkResume(cid,taskId,expectedRevision,{mode='strict',currentWorkspace,importEventIds=[]}={}){
    const c=this.inspect(cid,taskId),t=this.getTask(taskId);
    if(c.state!=='READY')throw new CheckpointError('checkpoint is not ready');
    if(t.revision!==expectedRevision)throw new StaleRevision('resume confirmation is stale');
    if(!['strict','practical'].includes(mode))throw new Error('mode must be strict or practical');
    if(mode==='strict'&&importEventIds.length)throw new CheckpointError('strict resume cannot import later events');
    for(const eventId of importEventIds)this.readEvent(taskId,eventId);
    if(currentWorkspace){const check=this.compareWorkspace(c.payload.workspace,currentWorkspace);if(check.status!=='match')throw new CheckpointError('workspace '+check.status+': '+check.reason)}
    return this.tx(()=>{
      const nt=this.bumpEpoch(taskId,expectedRevision);
      const seedEventIds=c.payload.notebookIds===undefined?this.checkpointEvents(cid,taskId).filter(e=>['user_input','model_response','tool_result'].includes(e.source)).map(e=>e.event_id):[];
      const selectedMemory=new Map(this.memory.checkpointVersions(c,nt.epoch).map(versionId=>{const memory=this.memory.version(versionId,taskId);return [memory.memory_id,versionId]}));
      for(const memory of this.memory.importVersions(taskId,importEventIds))selectedMemory.set(memory.memory_id,memory.version_id);
      const memoryVersionIds=[...selectedMemory.values()];
      const observerPending=this.notebook.checkpointObserverState(c,importEventIds);
      this.recordEvent(taskId,'resume',{checkpointId:cid,mode,sourceEpoch:c.epoch,importEventIds,memoryVersionIds,observerPending,notebookIds:c.payload.notebookIds??[],noteIds:c.payload.noteIds??[],seedEventIds},{epoch:nt.epoch});
      return {taskId,checkpointId:cid,mode,epoch:nt.epoch,contractRevision:nt.revision,payload:c.payload};
    });
  }
  events(taskId,epoch){const t=this.getTask(taskId);epoch??=t.epoch;if(epoch!==t.epoch)throw new ScopeError('only active epoch is readable');return this.db.prepare('SELECT * FROM events WHERE task_id=? AND epoch=? ORDER BY seq').all(taskId,epoch)}
  checkpointEvents(cid,taskId,{mode='strict',importEventIds=[]}={}){const c=this.inspect(cid,taskId),limit=c.payload.visibleSeq??0;let rows=this.db.prepare('SELECT * FROM events WHERE task_id=? AND epoch=? AND seq<=? ORDER BY seq').all(taskId,c.epoch,limit);if(mode==='practical'&&importEventIds.length){const placeholders=importEventIds.map(()=>'?').join(',');const extra=this.db.prepare(`SELECT * FROM events WHERE task_id=? AND event_id IN (${placeholders})`).all(taskId,...importEventIds);const seen=new Set(rows.map(x=>x.event_id));rows=[...rows,...extra.filter(x=>!seen.has(x.event_id)).map(x=>({...x,importedFromEpoch:x.epoch}))]}return rows}
  status(taskId){const t=this.getTask(taskId),c=this.row('SELECT checkpoint_id,state FROM checkpoints WHERE task_id=? ORDER BY created_at DESC LIMIT 1',taskId),e=this.row("SELECT source,payload,seq FROM events WHERE task_id=? AND source IN ('model_error','tool_result') ORDER BY seq DESC LIMIT 1",taskId);return {mode:this.mode,taskId,epoch:t.epoch,contractRevision:t.revision,runtime:this.runtimeState(taskId),checkpoint:c??null,lastError:e&&e.source==='model_error'?JSON.parse(e.payload):null,eventCount:this.row('SELECT COUNT(*) AS n FROM events WHERE task_id=?',taskId).n}}
}
